import { companyInfo } from './companyData';
import type { Language } from '../translations';

export interface ILegalSection {
  title: string;
  subtitle: string;
  s1Title: string;
  s1Text: string;
  s2Title: string;
  s2Text: string;
  s3Title: string;
  s3Text: string;
  s4Title: string;
  s4Text: string;
}

export const legalNoticeTexts: Record<Language, any> = {
  es: {
    title: 'Aviso Legal (LSSI-CE Art. 10)',
    subtitle: 'Información legal y condiciones de uso del sitio web de ARBOLEDA MULTISERVICIOS.',
    s1Title: '1. Datos Identificativos del Titular',
    s1Text: 'En cumplimiento del artículo 10 de la Ley 34/2002, de 11 de julio, de Servicios de la Sociedad de la Información y de Comercio Electrónico (LSSI-CE), se exponen los datos identificativos de la empresa titular:',
    labels: {
      tradeName: 'Denominación Comercial:',
      owners: 'Titulares de la Actividad:',
      nif: 'NIF / NIE:',
      address: 'Domicilio Físico:',
      phone: 'Contacto Directo / WhatsApp:',
      email: 'Correo Electrónico:',
    },
    s2Title: '2. Objeto y Ámbito de Aplicación',
    s2Text: `El presente Aviso Legal regula el acceso y uso del sitio web ${companyInfo.website}, que ARBOLEDA MULTISERVICIOS pone a disposición de los usuarios para informar sobre servicios profesionales de Climatización, Construcción, Reformas y Herrería en España. El acceso al portal implica la aceptación plena de estas disposiciones.`,
    s3Title: '3. Propiedad Intelectual e Industrial',
    s3Text: 'Todos los contenidos del sitio web (textos, logotipos, imágenes, fotografías de proyectos, software y diseño gráfico) son titularidad exclusiva de ARBOLEDA MULTISERVICIOS o de terceros autorizados. Queda prohibida su reproducción, distribución o comunicación pública sin autorización expresa.',
    s4Title: '4. Exención de Responsabilidad Técnica',
    s4Text: 'ARBOLEDA MULTISERVICIOS no se hace responsable de posibles fallos de conexión ajenos ni de daños derivados de un uso inadecuado del sitio web por parte del usuario.',
    closeBtn: 'Cerrar / Entendido',
  },
  va: {
    title: 'Avís Legal (LSSI-CE Art. 10)',
    subtitle: 'Informació legal i condicions d\'ús del lloc web d\'ARBOLEDA MULTISERVICIOS.',
    s1Title: '1. Dades Identificatives del Titular',
    s1Text: 'En compliment de l\'article 10 de la Llei 34/2002 (LSSI-CE), s\'exposen les dades identificatives de l\'empresa titular:',
    labels: {
      tradeName: 'Denominació Comercial:',
      owners: 'Titulars de l\'Activitat:',
      nif: 'NIF / NIE:',
      address: 'Domicili Físic:',
      phone: 'Contacte Directe / WhatsApp:',
      email: 'Correu Electrònic:',
    },
    s2Title: '2. Objecte i Àmbit d\'Aplicació',
    s2Text: `El present Avís Legal regula l'accés i ús del lloc web ${companyInfo.website} d'ARBOLEDA MULTISERVICIOS per a serveis de Climatització, Construcció, Reformes i Ferreria a Espanya.`,
    s3Title: '3. Propietat Intel·lectual i Industrial',
    s3Text: 'Tots els continguts d\'aquest portal són propietat exclusiva d\'ARBOLEDA MULTISERVICIOS o de llicenciants autoritzats.',
    s4Title: '4. Exempció de Responsabilitat Tècnica',
    s4Text: 'ARBOLEDA MULTISERVICIOS no es fa responsable d\'interrupcions tècniques alienes ni de danys derivats d\'un ús inadequat del lloc web.',
    closeBtn: 'Tancar / Entès',
  },
  en: {
    title: 'Legal Notice (LSSI-CE Art. 10)',
    subtitle: 'Legal information and terms of use for the ARBOLEDA MULTISERVICIOS website.',
    s1Title: '1. Owner Identification Data',
    s1Text: 'In compliance with Article 10 of Spanish Law 34/2002 (LSSI-CE), the following identification details of the operating business are provided:',
    labels: {
      tradeName: 'Commercial Name:',
      owners: 'Business Owners / Managers:',
      nif: 'Tax ID (NIF/NIE):',
      address: 'Physical Address:',
      phone: 'Direct Contact / WhatsApp:',
      email: 'Official Email:',
    },
    s2Title: '2. Purpose and Scope of Application',
    s2Text: `This Legal Notice governs access to and use of the website ${companyInfo.website}, provided by ARBOLEDA MULTISERVICIOS to inform about professional HVAC Air Conditioning, Building Works, Renovations, and Custom Ironwork in Spain. Accessing this portal implies full acceptance of these terms.`,
    s3Title: '3. Intellectual & Industrial Property',
    s3Text: 'All content on this website (texts, logos, images, project photos, software, and graphic design) is the exclusive property of ARBOLEDA MULTISERVICIOS or authorized licensors. Reproduction, distribution, or public display without prior written permission is strictly prohibited.',
    s4Title: '4. Technical Disclaimer',
    s4Text: 'ARBOLEDA MULTISERVICIOS is not liable for temporary service interruptions or damages resulting from improper user operation or third-party interference.',
    closeBtn: 'Close / Understood',
  },
  de: {
    title: 'Impressum / Rechtliche Hinweise (LSSI-CE)',
    subtitle: 'Rechtliche Informationen und Nutzungsbedingungen der Website von ARBOLEDA MULTISERVICIOS.',
    s1Title: '1. Angaben gemäß spanischem E-Commerce-Gesetz (LSSI-CE Art. 10)',
    s1Text: 'Gemäß Artikel 10 des Gesetzes 34/2002 (LSSI-CE) werden die folgenden Unternehmensdaten zur Verfügung gestellt:',
    labels: {
      tradeName: 'Handelsname:',
      owners: 'Geschäftsinhaber & Leitung:',
      nif: 'Steuernummer (NIF/NIE):',
      address: 'Geschäftsanschrift:',
      phone: 'Direktkontakt / WhatsApp:',
      email: 'Offizielle E-Mail:',
    },
    s2Title: '2. Gegenstand und Geltungsbereich',
    s2Text: `Dieses Impressum regelt den Zugriff und die Nutzung der Website ${companyInfo.website} von ARBOLEDA MULTISERVICIOS bezüglich Dienstleistungen in den Bereichen Klimatisierung, Bauwesen, Renovierungen und Metallbau in Spanien.`,
    s3Title: '3. Urheberrecht und Gewerblicher Rechtsschutz',
    s3Text: 'Alle Inhalte dieser Website (Texte, Logos, Bilder, Projektfotos, Software und Grafiken) sind geistiges Eigentum von ARBOLEDA MULTISERVICIOS. Jede unbefugte Vervielfältigung oder Verbreitung ist untersagt.',
    s4Title: '4. Haftungsausschluss',
    s4Text: 'ARBOLEDA MULTISERVICIOS übernimmt keine Haftung für vorübergehende Ausfälle oder Schäden, die durch unsachgemäße Nutzung des Nutzers entstehen.',
    closeBtn: 'Schließen / Verstanden',
  },
  fr: {
    title: 'Mentions Légales (LSSI-CE Art. 10)',
    subtitle: 'Informations légales et conditions d\'utilisation du site web d\'ARBOLEDA MULTISERVICIOS.',
    s1Title: '1. Données d\'Identification de l\'Exploitant',
    s1Text: 'Conformément à l\'article 10 de la loi espagnole 34/2002 (LSSI-CE), les coordonnées légales de l\'entreprise sont indiquées ci-dessous :',
    labels: {
      tradeName: 'Nom Commercial :',
      owners: 'Responsables Légaux :',
      nif: 'Numéro Fiscal (NIF/NIE) :',
      address: 'Adresse Physique :',
      phone: 'Contact Direct / WhatsApp :',
      email: 'Email Officiel :',
    },
    s2Title: '2. Objet et Champ d\'Application',
    s2Text: `Les présentes mentions légales régissent l'accès et l'utilisation du site web ${companyInfo.website} pour la présentation des prestations en Climatisation, Construction, Rénovation et Métallerie en Espagne par ARBOLEDA MULTISERVICIOS.`,
    s3Title: '3. Propriété Intellectuelle et Industrielle',
    s3Text: 'L\'ensemble des éléments du site (textes, visuels, photographies de chantiers, logos et architecture logicielle) est protégé par le droit d\'auteur et demeure la propriété d\'ARBOLEDA MULTISERVICIOS.',
    s4Title: '4. Exclusion de Responsabilité',
    s4Text: 'ARBOLEDA MULTISERVICIOS décline toute responsabilité en cas d\'interruption momentanée du service ou d\'utilisation frauduleuse par des tiers.',
    closeBtn: 'Fermer / Compris',
  },
  nl: {
    title: 'Juridische Kennisgeving (LSSI-CE Art. 10)',
    subtitle: 'Juridische informatie en gebruiksvoorwaarden van de website van ARBOLEDA MULTISERVICIOS.',
    s1Title: '1. Identificatiegegevens van de Ondernemer',
    s1Text: 'In overeenstemming met artikel 10 van de Spaanse Wet 34/2002 (LSSI-CE) worden de identificatiegegevens van de onderneming verstrekt:',
    labels: {
      tradeName: 'Handelsnaam:',
      owners: 'Bedrijfsleiders / Eigenaren:',
      nif: 'Fiscaal Nummer (NIF/NIE):',
      address: 'Fysiek Adres:',
      phone: 'Direct Contact / WhatsApp:',
      email: 'Officieel E-mailadres:',
    },
    s2Title: '2. Doel en Toepassingsgebied',
    s2Text: `Deze juridische kennisgeving regelt de toegang tot en het gebruik van de website ${companyInfo.website} van ARBOLEDA MULTISERVICIOS voor diensten op het gebied van Klimaatbeheersing (Airco), Bouw, Woningrenovatie en Metaalconstructies in Spanje.`,
    s3Title: '3. Intellectueel en Industrieel Eigendom',
    s3Text: 'Alle inhoud op deze website (teksten, logo’s, foto’s van projecten, code en grafisch ontwerp) is het exclusieve eigendom van ARBOLEDA MULTISERVICIOS. Reproductie of distributie zonder schriftelijke toestemming is verboden.',
    s4Title: '4. Technische Disclaimer',
    s4Text: 'ARBOLEDA MULTISERVICIOS is niet aansprakelijk voor tijdelijke storingen of schade veroorzaakt door onjuist gebruik van de website door de bezoeker.',
    closeBtn: 'Sluiten / Begrepen',
  },
  ru: {
    title: 'Правовая Информация (LSSI-CE Art. 10)',
    subtitle: 'Юридическая информация и условия использования веб-сайта ARBOLEDA MULTISERVICIOS.',
    s1Title: '1. Идентификационные Данные Компании',
    s1Text: 'В соответствии со статьей 10 Закона Испании 34/2002 (LSSI-CE) публикуются официальные реквизиты компании:',
    labels: {
      tradeName: 'Коммерческое Название:',
      owners: 'Владельцы и Руководители:',
      nif: 'Налоговый Номер (NIF/NIE):',
      address: 'Фактический Адрес:',
      phone: 'Прямой Контакт / WhatsApp:',
      email: 'Официальный Email:',
    },
    s2Title: '2. Предмет и Сфера Применения',
    s2Text: `Настоящее Правовое Уведомление регулирует доступ к сайту ${companyInfo.website} компании ARBOLEDA MULTISERVICIOS по услугам кондиционирования, строительства, ремонта и металлоконструкций в Испании.`,
    s3Title: '3. Интеллектуальная Собственность',
    s3Text: 'Все материалы сайта (тексты, фото объектов, логотипы, дизайн и код) являются исключительной собственностью ARBOLEDA MULTISERVICIOS. Любое копирование без разрешения запрещено.',
    s4Title: '4. Ограничение Ответственности',
    s4Text: 'ARBOLEDA MULTISERVICIOS не несет ответственности за временные сбои в сети интернет или последствия неправомерных действий третьих лиц.',
    closeBtn: 'Закрыть / Понятно',
  },
};

export const privacyTexts: Record<Language, any> = {
  es: {
    title: 'Política de Privacidad (RGPD UE 2016/679)',
    s1Title: '1. Responsable del Tratamiento',
    s1Text: `Responsables: Duban Dario Zapata Arboleda & Abel Castaño Arboleda (${companyInfo.name}).\nNIF/NIE: ${companyInfo.nif}\nDomicilio: ${companyInfo.address}\nEmail: ${companyInfo.email}\nWhatsApp: ${companyInfo.phone}`,
    s2Title: '2. Finalidad del Tratamiento',
    s2Text: 'Los datos facilitados a través de WhatsApp, llamadas o el cotizador interactivo se utilizan exclusivamente para atender consultas técnicas, elaborar presupuestos y coordinar visitas a domicilio para proyectos de climatización, obras y herrería.',
    s3Title: '3. Legitimación y Conservación',
    s3Text: 'La base jurídica es la aplicación de medidas precontractuales solicitadas por el usuario. Los datos se conservan únicamente durante la vigencia de la relación comercial o los plazos legales aplicables.',
    s4Title: '4. Derechos del Usuario (ARCO+)',
    s4Text: 'Puede ejercer sus derechos de acceso, rectificación, supresión, limitación y oposición en cualquier momento contactando directamente a nuestro WhatsApp o correo oficial.',
    closeBtn: 'Cerrar / Entendido',
  },
  va: {
    title: 'Política de Privacitat (RGPD UE 2016/679)',
    s1Title: '1. Responsable del Tractament',
    s1Text: `Responsables: Duban Dario Zapata Arboleda & Abel Castaño Arboleda (${companyInfo.name}).\nNIF/NIE: ${companyInfo.nif}\nDomicili: ${companyInfo.address}\nEmail: ${companyInfo.email}\nWhatsApp: ${companyInfo.phone}`,
    s2Title: '2. Finalitat del Tractament',
    s2Text: 'Les dades facilitades per WhatsApp o telefonada s\'utilitzen exclusivament per a gestionar consultes, elaborar pressupostos i coordinar visites a domicili.',
    s3Title: '3. Legitimació i Conservació',
    s3Text: 'La base jurídica és l\'aplicació de mesures precontractuals sol·licitades per l\'usuari. Les dades no es cedeixen a tercers.',
    s4Title: '4. Drets de l\'Usuari',
    s4Text: 'Pots exercir els teus drets d\'accés, rectificació, supressió i oposició contactant directament per WhatsApp o correu oficial.',
    closeBtn: 'Tancar / Entès',
  },
  en: {
    title: 'Privacy Policy (EU GDPR 2016/679)',
    s1Title: '1. Data Controller',
    s1Text: `Data Controllers: Duban Dario Zapata Arboleda & Abel Castaño Arboleda (${companyInfo.name}).\nTax ID: ${companyInfo.nif}\nAddress: ${companyInfo.address}\nEmail: ${companyInfo.email}\nWhatsApp: ${companyInfo.phone}`,
    s2Title: '2. Purpose of Data Processing',
    s2Text: 'Personal data provided via WhatsApp, phone calls, or the quote simulator is used exclusively to answer inquiries, prepare estimates, and schedule on-site technical visits for HVAC, construction, and metalwork projects.',
    s3Title: '3. Legal Basis and Retention',
    s3Text: 'The legal ground is the execution of pre-contractual measures requested by the user. Data is kept strictly for the duration of the commercial relationship or required statutory periods.',
    s4Title: '4. User Rights (GDPR)',
    s4Text: 'You may exercise your rights of access, rectification, erasure, restriction, and objection at any time by contacting us via WhatsApp or our official email.',
    closeBtn: 'Close / Understood',
  },
  de: {
    title: 'Datenschutzerklärung (EU-DSGVO 2016/679)',
    s1Title: '1. Verantwortliche Stelle',
    s1Text: `Verantwortliche: Duban Dario Zapata Arboleda & Abel Castaño Arboleda (${companyInfo.name}).\nSteuernummer: ${companyInfo.nif}\nAnschrift: ${companyInfo.address}\nE-Mail: ${companyInfo.email}\nWhatsApp: ${companyInfo.phone}`,
    s2Title: '2. Zweck der Datenverarbeitung',
    s2Text: 'Über WhatsApp oder Telefon bereitgestellte Daten werden ausschließlich zur Bearbeitung von Anfragen, Angebotserstellung und Terminierung kostenloser Vor-Ort-Besichtigungen verwendet.',
    s3Title: '3. Rechtsgrundlage und Speicherdauer',
    s3Text: 'Rechtsgrundlage ist die Erfüllung vorvertraglicher Maßnahmen. Daten werden nur so lange gespeichert, wie dies für die Geschäftsbeziehung oder gesetzliche Aufbewahrungsfristen erforderlich ist.',
    s4Title: '4. Ihre Rechte als Betroffener',
    s4Text: 'Sie haben jederzeit das Recht auf Auskunft, Berichtigung, Löschung und Widerspruch bezüglich Ihrer gespeicherten Daten.',
    closeBtn: 'Schließen / Verstanden',
  },
  fr: {
    title: 'Politique de Confidentialité (RGPD UE 2016/679)',
    s1Title: '1. Responsable du Traitement',
    s1Text: `Responsables : Duban Dario Zapata Arboleda & Abel Castaño Arboleda (${companyInfo.name}).\nNIF/NIE : ${companyInfo.nif}\nAdresse : ${companyInfo.address}\nEmail : ${companyInfo.email}\nWhatsApp : ${companyInfo.phone}`,
    s2Title: '2. Finalités du Traitement',
    s2Text: 'Les données transmises via WhatsApp ou appel sont exclusivement traitées pour répondre aux demandes, établir des devis et planifier des visites techniques pour travaux de climatisation, bâtiment et métallerie.',
    s3Title: '3. Base Juridique et Conservation',
    s3Text: 'Le traitement repose sur l\'exécution de mesures précontractuelles demandées par l\'utilisateur. Les données ne sont jamais cédées à des tiers.',
    s4Title: '4. Droits des Utilisateurs',
    s4Text: 'Vous pouvez exercer vos droits d\'accès, de rectification, d\'effacement et d\'opposition à tout moment en contactant notre service via WhatsApp ou email.',
    closeBtn: 'Fermer / Compris',
  },
  nl: {
    title: 'Privacybeleid (EU AVG/GDPR 2016/679)',
    s1Title: '1. Verwerkingsverantwoordelijke',
    s1Text: `Verantwoordelijken: Duban Dario Zapata Arboleda & Abel Castaño Arboleda (${companyInfo.name}).\nFiscaal Nr: ${companyInfo.nif}\nAdres: ${companyInfo.address}\nE-mail: ${companyInfo.email}\nWhatsApp: ${companyInfo.phone}`,
    s2Title: '2. Doeleinden van de Gegevensverwerking',
    s2Text: 'Gegevens die worden verstrekt via WhatsApp of telefoon worden uitsluitend gebruikt om offerteaanvragen te verwerken en inspectiebezoeken in te plannen voor airconditioning, bouw en staalconstructies.',
    s3Title: '3. Rechtsgrondslag en Bewaartermijn',
    s3Text: 'De verwerking is gebaseerd op precontractuele maatregelen op verzoek van de bezoeker. Gegevens worden nooit verkocht of aan derden doorgegeven.',
    s4Title: '4. Rechten van de Betrokkene',
    s4Text: 'U heeft te allen tijde het recht op inzage, rectificatie, verwijdering en bezwaar door contact op te nemen via WhatsApp of onze officiële e-mail.',
    closeBtn: 'Sluiten / Begrepen',
  },
  ru: {
    title: 'Политика Конфиденциальности (EU GDPR 2016/679)',
    s1Title: '1. Ответственные за Обработку Данных',
    s1Text: `Операторы данных: Duban Dario Zapata Arboleda & Abel Castaño Arboleda (${companyInfo.name}).\nНалоговый номер: ${companyInfo.nif}\nАдрес: ${companyInfo.address}\nEmail: ${companyInfo.email}\nWhatsApp: ${companyInfo.phone}`,
    s2Title: '2. Цели Обработки Данных',
    s2Text: 'Персональные данные, полученные через WhatsApp или телефон, используются исключительно для обработки заявок, расчета сметы и выезда мастера на объект.',
    s3Title: '3. Правовая Основа и Хранение',
    s3Text: 'Обработка основана на преддоговорных отношениях по запросу клиента. Данные строго конфиденциальны и не передаются третьим лицам.',
    s4Title: '4. Права Пользователя (GDPR)',
    s4Text: 'Вы имеете право на доступ, исправление, удаление и ограничение обработки ваших данных в любое время через WhatsApp или email.',
    closeBtn: 'Закрыть / Понятно',
  },
};

export const cookieTexts: Record<Language, any> = {
  es: {
    title: 'Política de Cookies (AEPD / UE)',
    s1Title: '1. ¿Qué son las Cookies?',
    s1Text: 'Las cookies son pequeños archivos de datos que se almacenan en su navegador para permitir el funcionamiento técnico y fluido del sitio web.',
    s2Title: '2. Cookies Utilizadas en ARBOLEDA MULTISERVICIOS',
    s2Text: 'Este portal utiliza exclusivamente cookies técnicas y de personalización esenciales (recordar el idioma seleccionado y el modo de color Claro/Oscuro). No utilizamos cookies publicitarias ni de seguimiento intrusivo.',
    s3Title: '3. Desactivación en el Navegador',
    s3Text: 'El usuario puede configurar o bloquear en cualquier momento las cookies a través de las opciones de privacidad de su navegador.',
    closeBtn: 'Cerrar / Entendido',
  },
  va: {
    title: 'Política de Cookies (AEPD / UE)',
    s1Title: '1. Què són les Cookies?',
    s1Text: 'Les cookies són xicotets fitxers que s\'emmagatzemen al navegador per a permetre el funcionament tècnic del lloc web.',
    s2Title: '2. Cookies Utilitzades a ARBOLEDA MULTISERVICIOS',
    s2Text: 'Aquest portal utilitza únicament cookies tècniques essencials (recordar la llengua i el mode Clar/Fosc). No fem servir cookies publicitàries.',
    s3Title: '3. Desactivació al Navegador',
    s3Text: 'Pots configurar o bloquejar les cookies en qualsevol moment des de les opcions del teu navegador.',
    closeBtn: 'Tancar / Entès',
  },
  en: {
    title: 'Cookie Policy (AEPD / EU)',
    s1Title: '1. What are Cookies?',
    s1Text: 'Cookies are small data files stored in your browser to enable smooth, secure technical operation of the website.',
    s2Title: '2. Cookies Used on ARBOLEDA MULTISERVICIOS',
    s2Text: 'This website uses only essential technical and preference cookies (remembering language choices and Dark/Light visual theme). We do not use third-party advertising or tracking cookies.',
    s3Title: '3. Browser Cookie Settings',
    s3Text: 'You can allow, block, or delete cookies at any time through your browser privacy settings.',
    closeBtn: 'Close / Understood',
  },
  de: {
    title: 'Cookie-Richtlinie (AEPD / EU)',
    s1Title: '1. Was sind Cookies?',
    s1Text: 'Cookies sind kleine Dateien, die auf Ihrem Endgerät gespeichert werden, um die technische Funktion der Website sicherzustellen.',
    s2Title: '2. Verwendete Cookies auf dieser Website',
    s2Text: 'Wir nutzen ausschließlich notwendige funktionale Cookies (Speicherung der Sprachauswahl und des Hell-/Dunkel-Modus). Keine Werbe- oder Tracking-Cookies.',
    s3Title: '3. Cookie-Verwaltung im Browser',
    s3Text: 'Sie können Cookies jederzeit in den Einstellungen Ihres Internet-Browsers verwalten oder löschen.',
    closeBtn: 'Schließen / Verstanden',
  },
  fr: {
    title: 'Politique de Cookies (AEPD / UE)',
    s1Title: '1. Que sont les Cookies ?',
    s1Text: 'Les cookies sont de petits fichiers stockés sur votre navigateur garantissant le bon fonctionnement technique du site.',
    s2Title: '2. Cookies Utilisés sur ARBOLEDA MULTISERVICIOS',
    s2Text: 'Ce site utilise uniquement des cookies techniques essentiels (mémorisation de la langue et du thème Clair/Sombre). Aucun cookie publicitaire tiers n\'est utilisé.',
    s3Title: '3. Gestion des Cookies',
    s3Text: 'Vous pouvez à tout moment autoriser, bloquer ou supprimer les cookies via les paramètres de votre navigateur.',
    closeBtn: 'Fermer / Compris',
  },
  nl: {
    title: 'Cookiebeleid (AEPD / EU)',
    s1Title: '1. Wat zijn Cookies?',
    s1Text: 'Cookies zijn kleine gegevensbestanden die in uw browser worden opgeslagen om de technische werking van de website te waarborgen.',
    s2Title: '2. Gebruikte Cookies op ARBOLEDA MULTISERVICIOS',
    s2Text: 'Deze website gebruikt uitsluitend noodzakelijke technische en voorkeurscookies (onthouden van taalkeuze en Donker/Licht-thema). Geen tracking- of advertentiecookies van derden.',
    s3Title: '3. Cookiebeheer in uw Browser',
    s3Text: 'U kunt cookies op elk gewenst moment toestaan, blokkeren of verwijderen via de instellingen van uw internetbrowser.',
    closeBtn: 'Sluiten / Begrepen',
  },
  ru: {
    title: 'Политика Использования Файлов Cookie (AEPD / EU)',
    s1Title: '1. Что Такое Файлы Cookie?',
    s1Text: 'Файлы cookie — это небольшие текстовые данные, сохраняемые в вашем браузере для обеспечения корректной работы сайта.',
    s2Title: '2. Файлы Cookie на Сайте ARBOLEDA MULTISERVICIOS',
    s2Text: 'Наш сайт использует исключительно необходимые технические cookie (сохранение языка и темы Светлая/Темная). Рекламные трекеры не используются.',
    s3Title: '3. Управление Cookie в Браузере',
    s3Text: 'Вы можете отключить или удалить файлы cookie в любое время в настройках конфиденциальности вашего веб-браузера.',
    closeBtn: 'Закрыть / Понятно',
  },
};

export const termsTexts: Record<Language, any> = {
  es: {
    title: 'Términos y Condiciones de Servicio',
    s1Title: '1. Presupuestos y Cotizaciones',
    s1Text: 'Las estimaciones del cotizador interactivo de WhatsApp son valores preliminares orientativos. El presupuesto formal y vinculante se formaliza tras la visita técnica presencial y medición exacta en el inmueble.',
    s2Title: '2. Ejecución y Garantías Profesionales',
    s2Text: 'Todos los servicios de climatización, obras integrales y herrería son ejecutados directamente bajo la dirección técnica de Duban Zapata y Abel Castaño, con garantía escrita y materiales homologados.',
    closeBtn: 'Cerrar / Entendido',
  },
  va: {
    title: 'Termes i Condicions de Servei',
    s1Title: '1. Pressupostos i Cotitzacions',
    s1Text: 'Les estimacions del cotitzador són orientatives. El pressupost formal i vinculant s\'emet després de la visita tècnica i mesurament in situ.',
    s2Title: '2. Execució i Garanties',
    s2Text: 'Tots els treballs de climatització, obra i ferreria s\'executen sota la direcció de Duban Zapata i Abel Castaño amb garantia per escrit.',
    closeBtn: 'Tancar / Entès',
  },
  en: {
    title: 'Terms & Conditions of Service',
    s1Title: '1. Estimates and Quotations',
    s1Text: 'Estimates generated via the interactive quote calculator are preliminary and non-binding. The final written quote is provided after the on-site technical inspection and accurate measurements.',
    s2Title: '2. Execution & Written Guarantee',
    s2Text: 'All HVAC, construction, and metal fabrication services are carried out under the direct supervision of Duban Zapata and Abel Castaño, backed by written warranties and certified materials.',
    closeBtn: 'Close / Understood',
  },
  de: {
    title: 'Allgemeine Dienstleistungsbedingungen',
    s1Title: '1. Kostenschätzungen und Angebote',
    s1Text: 'Die Berechnungen des interaktiven Kostenrechners sind unverbindliche Richtwerte. Das endgültige Angebot wird nach der kostenlosen Besichtigung vor Ort verbindlich erstellt.',
    s2Title: '2. Ausführung und Garantie',
    s2Text: 'Alle Arbeiten in den Bereichen Klimatisierung, Bau und Metalltechnik werden direkt durch Duban Zapata und Abel Castaño mit schriftlicher Qualitätsgarantie ausgeführt.',
    closeBtn: 'Schließen / Verstanden',
  },
  fr: {
    title: 'Conditions Générales de Service',
    s1Title: '1. Devis et Estimations',
    s1Text: 'Les estimations générées sur le simulateur sont purement indicatives. Le devis contractuel définitif est remis après la visite technique et la prise de cotes sur place.',
    s2Title: '2. Exécution des Travaux et Garanties',
    s2Text: 'Toutes les interventions en climatisation, rénovations et métallerie sont supervisées directement par Duban Zapata et Abel Castaño, avec garantie écrite.',
    closeBtn: 'Fermer / Compris',
  },
  nl: {
    title: 'Algemene Dienstvoorwaarden',
    s1Title: '1. Offertes en Prijsindicaties',
    s1Text: 'Schattingen via de online offertecalculator zijn voorlopig en indicatief. De definitieve bindende offerte wordt verstrekt na de gratis inspectie en exacte inmeting ter plaatse.',
    s2Title: '2. Uitvoering en Schriftelijke Garantie',
    s2Text: 'Alle werkzaamheden op het gebied van airconditioning, bouw en metaalbewerking worden direct uitgevoerd onder leiding van Duban Zapata en Abel Castaño, met officiële schriftelijke garantie.',
    closeBtn: 'Sluiten / Begrepen',
  },
  ru: {
    title: 'Условия Предоставления Услуг',
    s1Title: '1. Сметы и Расчеты',
    s1Text: 'Предварительные расчеты в калькуляторе WhatsApp носят ознакомительный характер. Официальная фиксированная смета составляется после бесплатного замера на объекте.',
    s2Title: '2. Исполнение и Официальная Гарантия',
    s2Text: 'Все работы по кондиционированию, строительству и металлоконструкциям выполняются под прямым руководством мастеров Дубана Сапаты и Абеля Кастаньо с письменной гарантией.',
    closeBtn: 'Закрыть / Понятно',
  },
};
